### PR TITLE
Add info on enabling git proxy

### PR DESCRIPTION
**Pull request by willfurnass**
Attempt to address https://github.com/jade-hpc-gpu/jade-hpc-gpu.github.io/issues/123.

### CODE REVIEW

**Comment by willfurnass** [comment]
@twinkarma Would be good to get reviewed by Jade admins

**Comment by willfurnass** [comment]
@twinkarma OK to merge?

**Comment by twinkarma** [comment]
What's the `http://dgj123b:3128/` address?

**Comment by willfurnass** [comment]
See https://github.com/jade-hpc-gpu/jade-hpc-gpu.github.io/issues/123#issuecomment-564648654.  Input from Hartree/ATOS admins may be useful.

**Comment by twinkarma** [comment]
Ah so it's from the `env`, should we not use

```
git config http.proxy $http_proxy
git config https.proxy $https_proxy
```

instead of the actual address?

**Comment by twinkarma** [comment]
@LiamATOS do you have any further comments with regards to this or with  jade-hpc-gpu/jade-hpc-gpu.github.io#123 ?

**Comment by LiamATOS** [comment]
No thats, fine, I force the proxy details in the environment config for all users.

I am not sure who manages the JADE documentation I am afraid.

Thanks

Liam

**Comment by willfurnass** [comment]
I've updated this PR so the aforementioned env vars are referenced.  However, would it not be cleaner to bake the proxy URLs into `/etc/gitconfig` instead?

**Comment by twinkarma** [comment]
Let's merge it in first then, we can remove this once the other method has been implemented

**Pull request merged**
